version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "20s", "npm", "start"]
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    # ports: 
    #   - "3000:3000"
    depends_on: 
       - db

  db:
    build:
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      
